### ISSUE TITLE
Visit not follow

### ISSUE THREAD

**Issue by joakimkasimir** [localfoodnodes/local-food-app#1]
I'm using android app.

If I browse nodes in the map, click on a node and choose visit (besök nod) it will open the node. But also it adds the node to my node list. The node shows in my node list in my desktop browser.

**Comment by davidajnered** [comment]
Thank you for your feedback. This was an intended decision to make it easier for users to get updates about nodes, but we're talking about going back to it being an opt-in feature so it will probably change in an upcoming update.
